In [1]:
print("hi")

hi


<h3>Q1</h3>

In [ ]:
# Write code to determine whether a number is even or odd and print it

number = 5
if number % 2 == 0:
    print(f"The {number} is even")
else:
    print(f"The {number} is odd")


The 5 is odd


<h3>Q2</h3>

In [ ]:
# For a given list of strings, check if the length of each string is even or odd. Print even or odd accordingly.

x = ['alphabets', 'numerics', 'data types', '123', 'wild' ,'abc', 'chars']
for word in x:
    if len(word)%2 == 0:
        print(f"The word {word} has even length")
    else:
        print(f"The word {word} has odd length")



The word alphabets has odd length
The word numerics has even length
The word data types has even length
The word 123 has odd length
The word wild has even length
The word abc has odd length
The word chars has odd length


<h3>Q3</h3>

In [ ]:
# Write a code to reverse the string hello using indexing and print it.
greeting='hello'

reversed_greeting = greeting[::-1]
print(reversed_greeting) 


olleh


<h3>Q4</h3>

In [ ]:
# For numbers in range 0 to 100, return a list of those that are multiple of 2 but not 5
def func():
    for num in range(0,101):
        if num %2 == 0 and num % 5 != 0 :
            yield num

l1= list(func())
print('List of multiples of 2 but not 5:',)
print(l1)

List of multiples of 2 but not 5:
[2, 4, 6, 8, 12, 14, 16, 18, 22, 24, 26, 28, 32, 34, 36, 38, 42, 44, 46, 48, 52, 54, 56, 58, 62, 64, 66, 68, 72, 74, 76, 78, 82, 84, 86, 88, 92, 94, 96, 98]


<h3>Q5</h3>

In [ ]:
# Write a Python function that accepts a string and calculates the number of upper case letters and lower case letters.


str = "Hello Mr. Rogers, how are you this fine Tuesday?"

def enum_cases(string):
    upper_case = 0
    lower_case = 0
    for char in string:
        if char.isupper():
            upper_case += 1
        elif char.islower():
            lower_case += 1

    return upper_case, lower_case

upper, lower = enum_cases(str)
print(f'Upper case characters:{upper}\nLower case characters: {lower}')

Upper case characters:4
Lower case characters: 33


<h3>Q6</h3>

In [ ]:
# Write a function that prints the integers from 1 to 100. But for multiples of three, print Fizz instead of the number,
# and for the multiples of five print Buzz. For numbers which are multiples of both three and five print FizzBuzz.

def special_print():
    for i in range(1,101):
        if i %3 == 0 and i%5 == 0:
            print("FizzBuzz")
        elif i%3 == 0:
            print("Fizz")
        elif i%5 == 0:
            print("Buzz")
        else:
            print(i)

special_print()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


<h3>Q7</h3>

In [ ]:
# Write a function, calculateSum(l,k) which will take a list, l and a number k as input and return two numbers from l that add up to k.

l = [1, 21, 3, 14, 5, 60, 7, 6]
k = 81

def calculate_sum(l,k):
    for i in range(len(l)):
        for j in range(i+1, len(l)):
            if l[i] + l[j] == k:
                return (l[i],l[j])

    return None

print(calculate_sum(l,k))

(21, 60)


<h3>Q8</h3>

In [ ]:
# Write a function, find_students that receives the students dictionary and an address, 
# and returns a list with names in sorted order of all students whose address matches the address in the argument.

def find_students(students, address):
    # Filter student names matching the address and return them sorted
    matching_students = [
        name for name, details in students.items() if details["address"] == address
    ]
    return sorted(matching_students)


students = {
    "Eesha": {"age": 21, "address": "Lahore"},
    "Ali": {"age": 6, "address": "Lahore"},
    "Ahmad": {"age": 15, "address": "Islamabad"},
}

print(find_students(students, "Lahore"))

['Ali', 'Eesha']


<h3>Q9</h3>

In [ ]:
# Given an unsorted list of integers, write a function first_missing_positive that returns the smallest missing positive integer.

def first_missing_positive(nums):
    n = len(nums)

    for i in range(n):
        while 1 <= nums[i] <= n and nums[nums[i] - 1] != nums[i]:
            nums[nums[i] - 1], nums[i] = nums[i], nums[nums[i] - 1]

    for i in range(n):
        if nums[i] != i + 1:
            return i + 1


    return n + 1
    
print(first_missing_positive([3, 4, -1, 1]))  # Output: 2
print(first_missing_positive([1, 2, 0]))      # Output: 3
print(first_missing_positive([7, 8, 9, 11]))  # Output: 1

2
3
1


<h3>Q10</h3>

In [ ]:
# Write a function flatten_dict that takes a nested dictionary and returns a flattened version where keys are concatenated with underscores for nested levels. 
# Handle edge cases like empty dictionaries or non-dictionary values.


[ ]

nested_dict = {
    'a': 1,
    'b': {
        'c': 2,
        'd': {
            'e': 3,
            'f': 4
        }
    },
    'g': 5
}

def flatten_dict(d, parent_key='', sep='_'):
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)
   

print(flatten_dict(nested_dict))
# Expected Output: {'a': 1, 'b_c': 2, 'b_d_e': 3, 'b_d_f': 4, 'g': 5}

{'a': 1, 'b_c': 2, 'b_d_e': 3, 'b_d_f': 4, 'g': 5}


<h3>Q11</h3>

In [ ]:
# Given a list of tuples representing student names and their scores, 
# write a function top_student that returns the name of the student with the highest score.
scores = [("Ali", 85), ("Ahmad", 92), ("Aisha", 78)]

def top_student(students):
    top_student =  max(students, key=lambda x: x[1])
    return top_student[0]

print(top_student(scores))

Ahmad


<h3>Q12</h3>

In [ ]:
# Write a function count_vowels that takes a string and returns a dictionary where the keys are vowels (a, e, i, o, u) 
# and the values are their respective counts in the string (case-insensitive).

text = "Hello, how are you today?"

def count_vowels(s):
    vowels = 'aeiou'
    vowel_count = {vowel: 0 for vowel in vowels}
    for char in s.lower():
        if char in vowels:
            vowel_count[char] += 1
    return vowel_count

print(count_vowels(text))

{'a': 2, 'e': 2, 'i': 0, 'o': 4, 'u': 1}


<h3>Q13</h3>

In [51]:
# Given a list of numbers, 
# write a function remove_outliers that removes the smallest and largest numbers from the list and returns the modified list.

numbers = [12, 3, 45, 7, 1, 67, 9]

def remove_outliers(lst):
    min_val = min(lst)
    max_val = max(lst)
    return [x for x in lst if x != min_val and x != max_val]

print(remove_outliers(numbers))

[12, 3, 45, 7, 9]


<h3>Q14</h3>

In [54]:
# Longest Consecutive Sequence in a List Given an unsorted list of integers, 
# write a function longest_consecutive_sequence that returns the length of the longest 
# consecutive sequence of numbers (e.g., [100, 4, 200, 1, 3, 2] → 4 because 1, 2, 3, 4 is the longest sequence).

nums = [100, 4, 200, 1, 3, 2, 101, 99, 102, 103, 104]

def longest_consecutive_sequence(nums):
    num_set = set(nums)
    longest_streak = 0

    for num in num_set:
        if num - 1 not in num_set:  # Start of a new sequence
            current_num = num
            current_streak = 1

            while current_num + 1 in num_set:
                current_num += 1
                current_streak += 1

            longest_streak = max(longest_streak, current_streak)

    return longest_streak

print(longest_consecutive_sequence(nums))

6


<h3>Q15</h3>

In [55]:
# Implement a Trie (Prefix Tree) Write a class Trie with methods insert(word), 
# search(word), and startsWith(prefix) to efficiently store and retrieve words.

class TrieNode:
    def __init__(self):
        self.children = {}
        self.is_end_of_word = False


class Trie:
    def __init__(self):
        self.root = TrieNode()

    def insert(self, word: str) -> None:
        node = self.root
        for char in word:
            if char not in node.children:
                node.children[char] = TrieNode()
            node = node.children[char]
        node.is_end_of_word = True

    def search(self, word: str) -> bool:
        node = self.root
        for char in word:
            if char not in node.children:
                return False
            node = node.children[char]
        return node.is_end_of_word

    def startsWith(self, prefix: str) -> bool:
        node = self.root
        for char in prefix:
            if char not in node.children:
                return False
            node = node.children[char]
        return True


# Testing the Trie
trie = Trie()
trie.insert("apple")
print(trie.search("apple"))   # Output: True
print(trie.search("app"))     # Output: False
print(trie.startsWith("app")) # Output: True
trie.insert("app")
print(trie.search("app"))     # Output: True

True
False
True
True


<h3>Q16</h3>

In [56]:
# # Design a CircularBuffer class that supports: append(x): Add an element to the buffer. If full, overwrite the oldest element.
# get(): Return the buffer as a list in insertion order.

class CircularBuffer:
    def __init__(self, size):
        self.size = size
        self.buffer = []

    def append(self, x):
        self.buffer.append(x)
        # If the buffer is full, remove the oldest element from the front
        if len(self.buffer) > self.size:
            self.buffer.pop(0)

    def get(self):
        # Since we remove from the front and add to the back, 
        # it is already in insertion order
        return self.buffer

cb = CircularBuffer(3)
cb.append(1)
cb.append(2)
cb.append(3)
print(cb.get())  # Output: [1, 2, 3]

cb.append(4)
print(cb.get())  # Output: [2, 3, 4]

[1, 2, 3]
[2, 3, 4]


<h3>Q17</h3>

In [57]:
# Write a function one_hot_encode that converts categorical
# labels (e.g., ["cat", "dog", "bird"]) into one-hot encoded arrays without using OneHotEncoder.

import numpy as np

def one_hot_encode(labels):
    """
    labels: List of categorical labels (e.g., ["cat", "dog", "cat"]).
    Returns a 2D NumPy array where each row is a one-hot vector.
    """
    # Extract unique labels while preserving the order of appearance
    unique_labels = list(dict.fromkeys(labels))
    
    # Create a mapping from label to its column index
    label_to_idx = {label: i for i, label in enumerate(unique_labels)}
    
    # Initialize a matrix of zeros
    n_samples = len(labels)
    n_classes = len(unique_labels)
    encoded = np.zeros((n_samples, n_classes))
    
    # Populate the matrix with 1s at the appropriate indices
    for i, label in enumerate(labels):
        encoded[i, label_to_idx[label]] = 1.0
        
    return encoded

# Test the function
labels = ["cat", "dog", "bird", "cat"]
print(one_hot_encode(labels))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
